<!doctype html>
<html>
<head>
<title>Blog | Thrive Proactive Health</title>
<!--Metas & Links-->
<?php require_once($_SERVER['DOCUMENT_ROOT'].'/assets/includes/head.php'); ?>
</head>

<body class="client-page">
<!--Site's Header-->
<?php require_once($_SERVER['DOCUMENT_ROOT'].'/assets/includes/header.php'); ?>

<div class="container spacing article">

	<!--Article-->
	<div class="row spacing">
		<div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
			<h2>5 Tips For 'Fit &amp; Fab; Total Body Wellness</h2>
			<p class="text-muted">May 27, 2017</p>
		</div>
		<div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>We recently got to spend an awesome morning with the fabulous <a href="http://wtkr.com/author/kristen-crowley/" target="_blank">>Kristen Crowley</a> and the WGNT/WTKR News 3 morning crew.  Kristen put together a '5 Days of Fit &amp; Fab' Total Body Wellness series and we were honored and grateful to participate!</p>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-2.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>In this series, we shared 5 quick tips to set your body up for success not only in the gym, but also in your everyday life. To learn the tips, you can read below to or watch the video clip <a href="http://wtkr.com/2017/05/24/5-days-to-fit-fab-top-5-ways-to-decrease-back-pain-and-improve-mobility/" target="_blank">HERE</a>!</p>
			<p><a href="http://wtkr.com/2017/05/24/5-days-to-fit-fab-top-5-ways-to-decrease-back-pain-and-improve-mobility/" target="_blank"><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-3.png" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></a></p>
			<h3>TIP #1 - AVOID OVER ENGAGING MUSCLES TO TRY TO STAND UP TALL</h3>
			<p>Truth be told, “good” posture is not as intuitive as most people would think. Our postural system is a very complex integration of our many systems and neurologically + respiratorily regulated. Our posture is not just a product of our musculoskeletal system and it is not solely about standing up tall. With this tip, we want people to understand that "good" posture should be effortless posture and you shouldn’t have to work so hard to get your body parts coordinated to stand up or sit up tall.</p>
			<p>If you are constantly trying to improve your posture and chase a "neutral spine"- you are working too hard, possibly doing more harm than good, and probably contributing to other health inefficiencies you may not even be associating with your postural system. Many people over extend and recruit too many muscles to stand up tall. They are compromising key spinal relationships and distorting the shape of our natural spinal curves in an attempt to "straighten up". Hyperextension can cause unnecessary pressure through the spine, improper joint loading and increases risk of injury for various joints. Large superficial muscles, like your paraspinals, lats, pecs, quads, and calves, need an opportunity to shut off and rest in order to optimize your postural and spinal support.</p>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-4.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>Lastly, it's important to understand, "good" posture is not static – it is DYNAMIC and always changing. A good postural system has VARIABILITY and knows how to move in and out of various positions with ease and efficiency. When working out, consider your movement profile, especially if you have any pain during or after your workout. To be Fit &amp; Fab, your body should NOT hurt! and if it does, you have movement and mechanical concerns you should get evaluated by biomechanical specialists (<a href="/postural.php">like us!</a>). Our bodies were designed to move and issues occur in posture and movement because our bodies get rotated in certain positions and various body segments have to adjust and compensate.</p>
			<h3>TIP #2 - SET YOUR DIAPHRAGM UP FOR SUCCESS</h3>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-5.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>The diaphragm is a very important CORE muscle. Just because we can't see it, or feel it, we should not forget to incorporate it in our quest to get 'Fit &amp; Fab'. Our diaphragm contracts over 20,000 times a day and can benefit from proper training just like any other skeletal muscle to assure it stays balanced and mechanically optimized.</p>
			<p>Breathing is foundational in how our core stabilizes and has a huge impact on various functions within our bodies. Restoring the diaphragms mechanical position can improve spinal, pelvic, and ribcage position and decrease joint torque and strain in the lower back, neck, shoulders and hips!</p>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-6.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>When training the diaphragm it is important to maximize the exhalation and that is why we use balloons! The balloons provide slight resistance and provide the system with biofeedback. With training the diaphragm we recommend doing it in various positions and incorporating other key postural muscles like your abdominal obliques, hamstrings/glutes, and shoulder stabilizers. We can go on and on about the diaphragm - it is truly one of the most important muscles to helping us feel 'Fit &amp; Fab'. Besides its mechanical influence on posture, it helps to relax the nervous system, improve immune and hormonal balance, regulate brain chemistry, balance emotions, and improves mental focus to help to reduce stress and anxiety.</p>
			<h3>TIP #3 - ALLOW YOUR RIBS TO MOVE</h3>
			<p>There are so many movements and exercises in the gym that lock our ribcages up. It's important for people to remember our ribcage was designed to be VERY mobile.</p>
			<p>Our ribcage is composed of 139 joints with architecture that is supposed to behave like a slinky or accordion (not like puffed up rigid steel bird cage!)</p>
			<p>When our ribcage movement becomes restricted and compromised, various parts of our body become vulnerable. Our spine (especially the lower back and neck), shoulders, hips, and even our knees start to compensate and rotate incorrectly - leading to injury over time. Our ribcage kinematics is where our bodies were designed to rotate, and if your not rotating through your ribcage you will get compensatory rotation in you lower back, hip or knee, etc. Think of the ribs as the long levers that direct spinal motion – the ribs need to move before the spine can flex and rotate.</p>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-7.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>Ribcages can become too stiff from over recruiting too many muscles to stand up tall, guarding and over stabilizing the body after injury, over bracing a neutral spine, or from improper breathing patterns. When your are hyperextended, your ribcage doesn’t move correctly and this places stress upon other structures of the body. Many people breathe in more air than they breathe out – in fact this is becoming an epidemic. Hyperinflation and over breathing has huge impact on various aspects of our health.</p>
			<h3>TIP #4 - WARM UP YOUR HAMSTRINGS</h3>
			<p>The hamstrings are very key muscles that control pelvic position and provide foundational support for our natural spinal curves.</p>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-8.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>Sitting is the new smoking. And too many of us, sit too much, our hamstrings shut off and become inhibited as the pelvic position becomes compromised due to tight hip flexors and lower backs.</p>
			<p>To help keep your posterior muscle chains balanced, think STRENTHEN - don't OVERlengthen! A lot of people worry about strengthening their lower back, but really to keep the posterior chains balanced, most need to STRENGTHEN THE HAMSTRINGS. Additionally, many people complain of “tight” hamstrings but in order to determine if the hamstrings need stretched or strengthened pelvic position needs to be respected. There is a difference between mechanical vs neurological tightness. We see many people, trying to stretch their hamstrings because they feel tight, when in reality their too long and neurologically excited. Regardless, with the hamstrings BOTH forms of tightness can be improved when pelvic position is optimized and well supported.</p>
			<p>When thinking about the hamstrings, consider them a key muscles to support the spine and good posture, they should be trained to engaged to support the pelvis and when the pelvis is in a better position you can then work all other core muscles better.</p>
			<h3>TIP #5 - TRAIN UNILATERALLY AND ASYMMETRICALLY</h3>
			<p>This is really a simple concept, but I realize that it can sound confusing at first. Luckily new fitness equipment is being designed constantly to help remedy our concerns with training too many movements symmetrically.  When I say training symmetrically, I mean, both arms (or both legs) doing the same thing at the same time. The fitness industry is influenced greatly by various lifting sports - powerlifting, olympic lifting, bodybuilding, etc. All of their training requires specificity but if you are not specifically training for a competition we encourage you to train in a way that will optimize your body's natural mechanical relationships.</p>
			<p><img class="img-responsive" src="/assets/images/old-site-imgs/blog37-9.jpeg" alt="5 Tips For 'Fit &amp; Fab; Total Body Wellness"></p>
			<p>Forcing symmetrical training may be doing more harm than good if you have imbalances through your core central structures. And regardless if you have imbalances or not, the two halves of our body were designed to move independently. Our extremities were designed to move alternating and reciprocally in gait, reaching, and rotation activities. Moreover, in our daily function, we don’t use our bodies symmetrically, and everybody is dominant on one side of their body or the other. This dominance is often exaggerated by the jobs we do or the sports we play. And the understanding of asymmetrical function, explains how pain and dysfunction develops only on side of the body, or why one side wears out before the other.</p>
			<p>It’s important to train both halves of the body. To optimize movement health and postural balance, we recommend incorporating sets of unilateral and alternating movement. This principles is especially important above the level of the diaphragm, because of how we use our bodies asymmetrically all the time for various reaching and rotational activities.</p>
			<p>For example: Training with unilaterally with alternation is a great functional way to train the shoulders and chest. Instead of using a barbell to chest press, use a dumbbell or kettlebell to press. With shoulder presses, use dumbbells and rest one at your shoulder level while the other presses up. When training the back with an activity like seated rows, use a single arm cable setting and row one arm back at a time. Or with the free motion or nautilus machines - alternate pulls from side to side so each side of the body is working independently.</p>
			<p>It is cool to mix it up – if doing 3-4 sets of an exercises – you may do the first 1-2 sets symmetrical and than the last two asymmetrically and unilaterally to help keep the ribs mobile. Remember tip #1 - the postural system needs variability. <strong>Mix it up, learn to breathe, respect your anatomy and mechanical architecture, and you will be on track for 'Fit and Fab' Total Body wellness!</strong></p>
			<p><a href="https://www.facebook.com/hashtag/neverstoplearning?source=feed_text&story_id=10213196411971531" target="_blank">#neverstoplearning</a> <a href="https://www.facebook.com/hashtag/enjoythejourney?source=feed_text&story_id=10213196411971531" target="_blank">#enjoythejourney</a>  <a href="https://www.facebook.com/hashtag/fitnesseducation?source=feed_text&story_id=10213196411971531" target="_blank">#fitnesseducation</a> <a href="https://www.facebook.com/hashtag/learntobreathe?source=feed_text&story_id=10213196411971531" target="_blank">#learntobreathe</a> <a href="https://www.facebook.com/hashtag/humanperformance?source=feed_text&story_id=10213196411971531" target="_blank">#humanperformance</a> <a href="https://www.facebook.com/hashtag/optimizethehumanmachine?source=feed_text&story_id=10213196411971531" target="_blank">#optimizethehumanmachine</a> <a href="https://www.facebook.com/hashtag/managegravity?source=feed_text&story_id=10213196411971531" target="_blank">#managegravity</a> <a href="https://www.facebook.com/hashtag/buildthesequence?source=feed_text&story_id=10213196411971531" target="_blank">#BuildTheSequence</a> <a href="https://www.facebook.com/hashtag/thrivevb?source=feed_text&story_id=10213196411971531" target="_blank">#thrivevb</a> <a href="https://www.facebook.com/hashtag/thrivefit?source=feed_text&story_id=10213196411971531" target="_blank">#thrivefit</a> <a href="https://www.facebook.com/hashtag/prination?source=feed_text&story_id=10213196411971531" target="_blank">#prination</a></p>
		</div>
	</div>
	
</div>


<!--Site's Footer-->
<?php require_once($_SERVER['DOCUMENT_ROOT'].'/assets/includes/footer.php'); ?>
</body>
</html>
